variables:
- name: Configuration
  value: Release
- name: PackageOutputPath
  value: $(Build.ArtifactStagingDirectory)

stages:

- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'windows-2019'
    steps:
    - checkout: self
      submodules: recursive
      clean: true

    - task: MSBuild@1
      displayName: Build
      inputs:
        configuration: $(Configuration)
        msbuildArguments: -r

    - task: VSTest@2
      displayName: Test
      inputs:
        testAssemblyVer2: src/**/bin/**/*Tests.dll
        runInParallel: true
        codeCoverageEnabled: true
        publishRunAttachments: true

    - task: PublishBuildArtifacts@1
      displayName: Upload
      condition: succeeded()
      inputs:
        PathtoPublish: $(Build.ArtifactStagingDirectory)
        ArtifactName: package
        ArtifactType: Container